const  productData =  [
  {
    "product_id": 1,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaRE92.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza RE92",
    "average_rating": "3.4",
    "review_count": "(606)",
    "product_specs": "Performance All-Season Tires",
    "stability": "Stability: 9.1",
    "traction": "Traction: 8.1",
    "dry_traction": "Dry Traction: 9.3",
    "ride_comfort": "Ride Comfort: 8.3",
    "tire_wear": "Tire Wear: 8.5",
    "wet_traction": "Wet Traction: 8.5",
    "noise_level": "Noise Level: 8.3"
  },
  {
    "product_id": 2,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaEL42.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza EL42",
    "average_rating": "3.4",
    "review_count": "(326)",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 8.9",
    "traction": "Traction: 8.3",
    "dry_traction": "Dry Traction: 9.1",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 8.7",
    "wet_traction": "Wet Traction: 8.7",
    "noise_level": "Noise Level: 8.9"
  },
  {
    "product_id": 3,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaER33.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza ER33",
    "average_rating": "3.8",
    "review_count": "(5)",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 4,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/FirehawkGT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Firehawk GT",
    "average_rating": "3.0",
    "review_count": "(11)",
    "product_specs": "Performance All-Season Tires",
    "stability": "Stability: 8.4",
    "traction": "Traction: 7.5",
    "dry_traction": "Dry Traction: 8.7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7.9",
    "wet_traction": "Wet Traction: 8.1",
    "noise_level": "Noise Level: 7.6"
  },
  {
    "product_id": 5,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/R265.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone R265",
    "average_rating": "4.0",
    "review_count": "(1)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 10",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 10",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 10"
  },
  {
    "product_id": 6,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHLAlenza.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/L Alenza",
    "average_rating": "4.3",
    "review_count": "(1014)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 8.8",
    "traction": "Traction: 8.3",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 8.7",
    "tire_wear": "Tire Wear: 8.3",
    "wet_traction": "Wet Traction: 8.8",
    "noise_level": "Noise Level: 8.4"
  },
  {
    "product_id": 7,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TransforceHT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Transforce HT",
    "average_rating": "3.6",
    "review_count": "(126)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 8.3",
    "traction": "Traction: 7.8",
    "dry_traction": "Dry Traction: 8.8",
    "ride_comfort": "Ride Comfort: 8.1",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 8.3",
    "noise_level": "Noise Level: 8.1"
  },
  {
    "product_id": 8,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DestinationAT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Destination A/T",
    "average_rating": "4.6",
    "review_count": "(1240)",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 8.6",
    "traction": "Traction: 8.3",
    "dry_traction": "Dry Traction: 9.1",
    "ride_comfort": "Ride Comfort: 8.6",
    "tire_wear": "Tire Wear: 8.3",
    "wet_traction": "Wet Traction: 8.6",
    "noise_level": "Noise Level: 8.4"
  },
  {
    "product_id": 9,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TransforceAT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Transforce A/T",
    "average_rating": "3.5",
    "review_count": "(161)",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 8.8",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 9.1",
    "ride_comfort": "Ride Comfort: 8.2",
    "tire_wear": "Tire Wear: 8.5",
    "wet_traction": "Wet Traction: 8.2",
    "noise_level": "Noise Level: 8.3"
  },
  {
    "product_id": 10,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHPSport.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/P Sport",
    "average_rating": "4.1",
    "review_count": "(44)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 7.8",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 6.5",
    "tire_wear": "Tire Wear: 6.5",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 6.8"
  },
  {
    "product_id": 11,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/FR710.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone FR710",
    "average_rating": "3.7",
    "review_count": "(130)",
    "product_specs": "Car & Minivan All-Season Tires",
    "stability": "Stability: 8.6",
    "traction": "Traction: 7.9",
    "dry_traction": "Dry Traction: 8.9",
    "ride_comfort": "Ride Comfort: 8.5",
    "tire_wear": "Tire Wear: 8.3",
    "wet_traction": "Wet Traction: 8.4",
    "noise_level": "Noise Level: 8.2"
  },
  {
    "product_id": 12,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PS830850.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Primewell_logo.png",
    "product_name": "Primewell PS830/850",
    "average_rating": "3.2",
    "review_count": "(26)",
    "product_specs": "Economy  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 6",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 6",
    "wet_traction": "Wet Traction: 6",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 13,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuravisR500HD.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Duravis R500 HD",
    "average_rating": "4.7",
    "review_count": "(3)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 6",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 6",
    "ride_comfort": "Ride Comfort: 6",
    "tire_wear": "Tire Wear: 4",
    "wet_traction": "Wet Traction: 3",
    "noise_level": "Noise Level: 6"
  },
  {
    "product_id": 14,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHL400.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/L400",
    "average_rating": "3.4",
    "review_count": "(115)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 8.6",
    "traction": "Traction: 7.5",
    "dry_traction": "Dry Traction: 8.8",
    "ride_comfort": "Ride Comfort: 8.5",
    "tire_wear": "Tire Wear: 7.8",
    "wet_traction": "Wet Traction: 8.4",
    "noise_level": "Noise Level: 8.3"
  },
  {
    "product_id": 15,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuravisM700.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Duravis M700",
    "average_rating": "4.6",
    "review_count": "(18)",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 10",
    "traction": "Traction: 10",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 10",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 10"
  },
  {
    "product_id": 16,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaRE050ARFT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza RE050A RFT",
    "average_rating": "2.5",
    "review_count": "(110)",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "Stability: 9.3",
    "traction": "Traction: 8.5",
    "dry_traction": "Dry Traction: 9.3",
    "ride_comfort": "Ride Comfort: 8.3",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 7.7"
  },
  {
    "product_id": 17,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaRE050A.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza RE050A",
    "average_rating": "4.0",
    "review_count": "(298)",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "Stability: 10",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 18,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerATRHS.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler A/T RH-S",
    "average_rating": "4.2",
    "review_count": "(113)",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 8.5",
    "traction": "Traction: 8.4",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 8.3",
    "tire_wear": "Tire Wear: 7.6",
    "wet_traction": "Wet Traction: 8.1",
    "noise_level": "Noise Level: 8.2"
  },
  {
    "product_id": 19,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHT684II.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/T 684 II",
    "average_rating": "3.7",
    "review_count": "(184)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 8.5",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 8.9",
    "ride_comfort": "Ride Comfort: 8.4",
    "tire_wear": "Tire Wear: 8.1",
    "wet_traction": "Wet Traction: 8.4",
    "noise_level": "Noise Level: 8.2"
  },
  {
    "product_id": 20,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHT687.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/T 687",
    "average_rating": "3.3",
    "review_count": "(138)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 8.4",
    "traction": "Traction: 7.7",
    "dry_traction": "Dry Traction: 8.6",
    "ride_comfort": "Ride Comfort: 8.3",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 8.2",
    "noise_level": "Noise Level: 7.9"
  },
  {
    "product_id": 21,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHT689.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/T 689",
    "average_rating": "3.5",
    "review_count": "(138)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 8.5",
    "traction": "Traction: 7.9",
    "dry_traction": "Dry Traction: 8.7",
    "ride_comfort": "Ride Comfort: 8.5",
    "tire_wear": "Tire Wear: 8.4",
    "wet_traction": "Wet Traction: 8.3",
    "noise_level": "Noise Level: 8.4"
  },
  {
    "product_id": 22,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHT840.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/T 840",
    "average_rating": "4.1",
    "review_count": "(77)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 9",
    "traction": "Traction: 8.6",
    "dry_traction": "Dry Traction: 9.3",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 9.1",
    "wet_traction": "Wet Traction: 8.9",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 23,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHL400MOE.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/L 400 MOE",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 24,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaEL470.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza EL470",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 8.3",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 8.7",
    "tire_wear": "Tire Wear: 8.3",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 8.3"
  },
  {
    "product_id": 25,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHL400RFT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/L 400 RFT",
    "average_rating": "5.0",
    "review_count": "(1)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 26,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerATD693II.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler A/T D693 II",
    "average_rating": "",
    "review_count": "",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 10",
    "traction": "Traction: 9",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 10",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 27,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaER3002RFT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza ER300-2 RFT",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 5.5",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 5.5",
    "ride_comfort": "Ride Comfort: 5.5",
    "tire_wear": "Tire Wear: 3.5",
    "wet_traction": "Wet Traction: 5.5",
    "noise_level": "Noise Level: 5.5"
  },
  {
    "product_id": 28,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaRE92A.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza RE92A",
    "average_rating": "3.4",
    "review_count": "(131)",
    "product_specs": "Performance All-Season Tires",
    "stability": "Stability: 9",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 29,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaS02A.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza S-02A",
    "average_rating": "4.0",
    "review_count": "(33)",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "",
    "traction": "",
    "dry_traction": "",
    "ride_comfort": "",
    "tire_wear": "",
    "wet_traction": "",
    "noise_level": ""
  },
  {
    "product_id": 30,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaEL40002T.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza EL400-02 T",
    "average_rating": "3.2",
    "review_count": "(211)",
    "product_specs": "Car & Minivan All-Season Tires",
    "stability": "Stability: 8.7",
    "traction": "Traction: 8.3",
    "dry_traction": "Dry Traction: 9.1",
    "ride_comfort": "Ride Comfort: 8.7",
    "tire_wear": "Tire Wear: 8.4",
    "wet_traction": "Wet Traction: 8.6",
    "noise_level": "Noise Level: 8.6"
  },
  {
    "product_id": 31,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaEL40002.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza EL400-02",
    "average_rating": "3.2",
    "review_count": "(211)",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 9.1",
    "traction": "Traction: 8.6",
    "dry_traction": "Dry Traction: 9.3",
    "ride_comfort": "Ride Comfort: 8.8",
    "tire_wear": "Tire Wear: 8.3",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8.6"
  },
  {
    "product_id": 32,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaEL42RFT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza EL42 RFT",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 10",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 33,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaEL40002RFT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza EL400-02 RFT",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 34,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaRE050AIRFT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza RE050A I RFT",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 35,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaS001.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza S001",
    "average_rating": "3.1",
    "review_count": "(29)",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 36,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/EcopiaEP422.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Ecopia EP422",
    "average_rating": "3.8",
    "review_count": "(149)",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 8.8",
    "traction": "Traction: 8.4",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 8.8",
    "tire_wear": "Tire Wear: 8.8",
    "wet_traction": "Wet Traction: 8.7",
    "noise_level": "Noise Level: 8.7"
  },
  {
    "product_id": 37,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHL422Ecopia.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/L 422 Ecopia",
    "average_rating": "4.3",
    "review_count": "(139)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 9.1",
    "traction": "Traction: 9.2",
    "dry_traction": "Dry Traction: 9.4",
    "ride_comfort": "Ride Comfort: 9.1",
    "tire_wear": "Tire Wear: 8.7",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 9.1"
  },
  {
    "product_id": 38,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/WinterforceLT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Winterforce LT",
    "average_rating": "4.0",
    "review_count": "(37)",
    "product_specs": "Snow  - Commercial LT Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 10",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 39,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaEL400RFT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza EL400 RFT",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Car & Minivan All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 40,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaEL40002MOE.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza EL400-02 MOE",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 41,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ValeraHTLTR.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Primewell_logo.png",
    "product_name": "Primewell Valera H/T LTR",
    "average_rating": "3.6",
    "review_count": "(7)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 6",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 42,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ValeraHT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Primewell_logo.png",
    "product_name": "Primewell Valera H/T",
    "average_rating": "3.6",
    "review_count": "(16)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 6",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 43,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/AffinityTouringS4FF.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Affinity Touring S4 FF",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Car & Minivan All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 44,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/BlizzakLM32.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Blizzak LM-32",
    "average_rating": "4.0",
    "review_count": "(7)",
    "product_specs": "Snow  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 10",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 45,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHPSportAS.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/P Sport AS",
    "average_rating": "2.8",
    "review_count": "(71)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 46,
    "product_img": "https://www.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/NoPic.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/P Sport MOE",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 47,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaS001RFT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza S001 RFT",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 48,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DestinationLE2.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Destination LE2",
    "average_rating": "3.9",
    "review_count": "(303)",
    "product_specs": "CUV/SUV Highway All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 9",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 49,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaRE97AS.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza RE97AS",
    "average_rating": "3.1",
    "review_count": "(29)",
    "product_specs": "Performance All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 10",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 50,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHLAlenzaPlus.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/L Alenza Plus",
    "average_rating": "3.7",
    "review_count": "(118)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 9",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 10",
    "tire_wear": "Tire Wear: 10",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 10"
  },
  {
    "product_id": 51,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ValeraSportAS.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Primewell_logo.png",
    "product_name": "Primewell Valera Sport AS",
    "average_rating": "3.0",
    "review_count": "(27)",
    "product_specs": "Ultra High Performance All Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 6",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 6",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 52,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DriveGuard.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone DriveGuard",
    "average_rating": "2.9",
    "review_count": "(10)",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 53,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/EcopiaEP422Plus.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Ecopia EP422 Plus",
    "average_rating": "3.1",
    "review_count": "(103)",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 9",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 54,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/BlizzakDMV2.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Blizzak DM-V2",
    "average_rating": "4.9",
    "review_count": "(41)",
    "product_specs": "Snow  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 10",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 55,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/FT140.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone FT140",
    "average_rating": "2.5",
    "review_count": "(10)",
    "product_specs": "Car & Minivan All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 56,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaEL440.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza EL440",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "",
    "traction": "",
    "dry_traction": "",
    "ride_comfort": "",
    "tire_wear": "",
    "wet_traction": "",
    "noise_level": ""
  },
  {
    "product_id": 57,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/FirehawkIndy500.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Firehawk Indy 500",
    "average_rating": "4.4",
    "review_count": "(91)",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "Stability: 8.5",
    "traction": "Traction: 7.5",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 8.7",
    "tire_wear": "Tire Wear: 8.6",
    "wet_traction": "Wet Traction: 8.5",
    "noise_level": "Noise Level: 8.2"
  },
  {
    "product_id": 58,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/FirehawkAS.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Firehawk AS",
    "average_rating": "3.8",
    "review_count": "(78)",
    "product_specs": "Ultra High Performance All Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 10",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 59,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DriveGuardCUV.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone DriveGuard CUV",
    "average_rating": "3.8",
    "review_count": "(66)",
    "product_specs": "CUV/SUV Highway All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 60,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuravisR238.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Duravis R238",
    "average_rating": "4.6",
    "review_count": "(18)",
    "product_specs": "Highway  Tires",
    "stability": "",
    "traction": "",
    "dry_traction": "",
    "ride_comfort": "",
    "tire_wear": "",
    "wet_traction": "",
    "noise_level": ""
  },
  {
    "product_id": 61,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHT685.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/T 685",
    "average_rating": "2.5",
    "review_count": "(15)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 10",
    "tire_wear": "Tire Wear: 10",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 10"
  },
  {
    "product_id": 62,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ALLSEASON.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone ALL SEASON",
    "average_rating": "2.9",
    "review_count": "(55)",
    "product_specs": "Car & Minivan All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 63,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TransforceAT2.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Transforce AT2",
    "average_rating": "3.0",
    "review_count": "(40)",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 64,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/OPENCOUNTRYMT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Toyo_logo.png",
    "product_name": "Toyo OPEN COUNTRY M/T",
    "average_rating": "5.0",
    "review_count": "(1)",
    "product_specs": "Max Traction  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 6",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 6"
  },
  {
    "product_id": 65,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/OPENCOUNTRYRT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Toyo_logo.png",
    "product_name": "Toyo OPEN COUNTRY R/T",
    "average_rating": "5.0",
    "review_count": "(1)",
    "product_specs": "Max Traction  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 66,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerHLAlenza001.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler H/L Alenza 001",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Highway  Tires",
    "stability": "",
    "traction": "",
    "dry_traction": "",
    "ride_comfort": "",
    "tire_wear": "",
    "wet_traction": "",
    "noise_level": ""
  },
  {
    "product_id": 67,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/Winterforce2.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Winterforce 2",
    "average_rating": "4.5",
    "review_count": "(15)",
    "product_specs": "Snow  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 10",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 6"
  },
  {
    "product_id": 68,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaT005.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza T005",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "",
    "traction": "",
    "dry_traction": "",
    "ride_comfort": "",
    "tire_wear": "",
    "wet_traction": "",
    "noise_level": ""
  },
  {
    "product_id": 69,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/Winterforce2UV.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Winterforce 2 UV",
    "average_rating": "2.9",
    "review_count": "(7)",
    "product_specs": "Snow  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 10",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 70,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DestinationMT2.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Destination M/T2",
    "average_rating": "4.3",
    "review_count": "(509)",
    "product_specs": "Max Traction  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 71,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ExtensaHPII.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Toyo_logo.png",
    "product_name": "Toyo Extensa HPII",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Ultra High Performance All Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 5",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 6",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 72,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerATRevo3.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler A/T Revo 3",
    "average_rating": "3.9",
    "review_count": "(70)",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 73,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DuelerATRevo3LT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Dueler A/T Revo 3 - LT",
    "average_rating": "3.9",
    "review_count": "(72)",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 74,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/EcopiaHL422Plus.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Ecopia H/L 422 Plus",
    "average_rating": "2.5",
    "review_count": "(123)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 9",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 75,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ALENZAAS02.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone ALENZA A/S 02",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Highway  Tires",
    "stability": "",
    "traction": "",
    "dry_traction": "",
    "ride_comfort": "",
    "tire_wear": "",
    "wet_traction": "",
    "noise_level": ""
  },
  {
    "product_id": 76,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TransforceCV.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Transforce CV",
    "average_rating": "3.0",
    "review_count": "(2)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 77,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaT005A.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza T005A",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "",
    "traction": "",
    "dry_traction": "",
    "ride_comfort": "",
    "tire_wear": "",
    "wet_traction": "",
    "noise_level": ""
  },
  {
    "product_id": 78,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/OPENCOUNTRYATII.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Toyo_logo.png",
    "product_name": "Toyo OPEN COUNTRY A/T II",
    "average_rating": "",
    "review_count": "",
    "product_specs": "All Terrain  Tires",
    "stability": "",
    "traction": "",
    "dry_traction": "",
    "ride_comfort": "",
    "tire_wear": "",
    "wet_traction": "",
    "noise_level": ""
  },
  {
    "product_id": 79,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PROXESR1R.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Toyo_logo.png",
    "product_name": "Toyo PROXES R1R",
    "average_rating": "5.0",
    "review_count": "(1)",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 6",
    "tire_wear": "Tire Wear: 4",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 6"
  },
  {
    "product_id": 80,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PROXESSTIII.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Toyo_logo.png",
    "product_name": "Toyo PROXES ST III",
    "average_rating": "5.0",
    "review_count": "(1)",
    "product_specs": "Highway All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 6",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 6",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 81,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PS890Touring.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Primewell_logo.png",
    "product_name": "Primewell PS890 Touring",
    "average_rating": "3.4",
    "review_count": "(23)",
    "product_specs": "Mass Market  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 82,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TransforceHT2.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Transforce HT2",
    "average_rating": "3.2",
    "review_count": "(21)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 83,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaQUIETTRACK.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza QUIETTRACK",
    "average_rating": "3.7",
    "review_count": "(108)",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 10",
    "tire_wear": "Tire Wear: 10",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 10"
  },
  {
    "product_id": 84,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/BlizzakWS90.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Blizzak WS90",
    "average_rating": "4.4",
    "review_count": "(31)",
    "product_specs": "Snow  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 10",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 85,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/WEATHERGRIP.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone WEATHERGRIP",
    "average_rating": "4.2",
    "review_count": "(75)",
    "product_specs": "Car & Minivan All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 10",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 86,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PROXESSport.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Toyo_logo.png",
    "product_name": "Toyo PROXES Sport",
    "average_rating": "5.0",
    "review_count": "(1)",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 6",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 87,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/OPENCOUNTRYHTII.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Toyo_logo.png",
    "product_name": "Toyo OPEN COUNTRY HTII",
    "average_rating": "5.0",
    "review_count": "(1)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 10",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 88,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/AllSeason.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Primewell_logo.png",
    "product_name": "Primewell All Season",
    "average_rating": "3.4",
    "review_count": "(11)",
    "product_specs": "Economy  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 6",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 6",
    "wet_traction": "Wet Traction: 6",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 89,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaS007ARFT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza S007 A RFT",
    "average_rating": "4.0",
    "review_count": "(1)",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 90,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DestinationAT2.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Destination A/T2",
    "average_rating": "4.8",
    "review_count": "(54)",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 9",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 91,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DestinationXT.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Destination X/T",
    "average_rating": "4.6",
    "review_count": "(44)",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 9",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 92,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ALENZASportAS.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone ALENZA Sport A/S",
    "average_rating": "1.0",
    "review_count": "(1)",
    "product_specs": "Highway  Tires",
    "stability": "",
    "traction": "",
    "dry_traction": "",
    "ride_comfort": "",
    "tire_wear": "",
    "wet_traction": "",
    "noise_level": ""
  },
  {
    "product_id": 93,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TuranzaLS100.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Turanza LS100",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "",
    "traction": "",
    "dry_traction": "",
    "ride_comfort": "",
    "tire_wear": "",
    "wet_traction": "",
    "noise_level": ""
  },
  {
    "product_id": 94,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DestinationLE3.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Destination LE3",
    "average_rating": "4.4",
    "review_count": "(213)",
    "product_specs": "CUV/SUV Highway All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 9",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 95,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/BlizzakLM005.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Blizzak LM005",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Snow  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 10",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 96,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaSport.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza Sport",
    "average_rating": "2.8",
    "review_count": "(70)",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 0",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 97,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaRE980AS+.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza RE980AS+",
    "average_rating": "4.0",
    "review_count": "(46)",
    "product_specs": "Performance All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 10",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 98,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/WEATHERPEAK.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone WEATHERPEAK",
    "average_rating": "4.0",
    "review_count": "(9)",
    "product_specs": "Car & Minivan All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 9",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 99,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ALENZAASULTRA.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone ALENZA AS ULTRA",
    "average_rating": "4.4",
    "review_count": "(74)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 9",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 10",
    "tire_wear": "Tire Wear: 10",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 10"
  },
  {
    "product_id": 100,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ExtensaASII.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Toyo_logo.png",
    "product_name": "Toyo Extensa A/S II",
    "average_rating": "5.0",
    "review_count": "(2)",
    "product_specs": "Car & Minivan All-Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 6",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 101,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/OPENCOUNTRYATIII.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Toyo_logo.png",
    "product_name": "Toyo OPEN COUNTRY A/T III",
    "average_rating": "5.0",
    "review_count": "(1)",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 10",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 10",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 102,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PROXESSportAS.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Toyo_logo.png",
    "product_name": "Toyo PROXES Sport A/S",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Ultra High Performance All Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 6",
    "dry_traction": "Dry Traction: 9",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 9",
    "noise_level": "Noise Level: 9"
  },
  {
    "product_id": 103,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ALLSeason.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/SUREDRIVE_logo.png",
    "product_name": "SUREDRIVE ALL-Season",
    "average_rating": "4.8",
    "review_count": "(10)",
    "product_specs": "Economy  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 7",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 104,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ALLTERRAINLTR.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/SUREDRIVE_logo.png",
    "product_name": "SUREDRIVE ALL-TERRAIN LTR",
    "average_rating": "",
    "review_count": "",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 105,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/ALLTERRAIN.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/SUREDRIVE_logo.png",
    "product_name": "SUREDRIVE ALL-TERRAIN",
    "average_rating": "5.0",
    "review_count": "(1)",
    "product_specs": "All Terrain  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 106,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/HIGHWAY.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/SUREDRIVE_logo.png",
    "product_name": "SUREDRIVE HIGHWAY",
    "average_rating": "2.6",
    "review_count": "(5)",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 6",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 107,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/HIGHWAYLTR.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/SUREDRIVE_logo.png",
    "product_name": "SUREDRIVE HIGHWAY LTR",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Highway  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 6",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 108,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/Sport.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/SUREDRIVE_logo.png",
    "product_name": "SUREDRIVE Sport",
    "average_rating": "5.0",
    "review_count": "(5)",
    "product_specs": "Ultra High Performance All Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 7",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 9",
    "wet_traction": "Wet Traction: 7",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 109,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/TouringAS.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/SUREDRIVE_logo.png",
    "product_name": "SUREDRIVE Touring A/S",
    "average_rating": "4.3",
    "review_count": "(9)",
    "product_specs": "Mass Market  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 6",
    "dry_traction": "Dry Traction: 7",
    "ride_comfort": "Ride Comfort: 7",
    "tire_wear": "Tire Wear: 6",
    "wet_traction": "Wet Traction: 6",
    "noise_level": "Noise Level: 7"
  },
  {
    "product_id": 110,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/DriveGuardPlus.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone DriveGuard Plus",
    "average_rating": "4.5",
    "review_count": "(6)",
    "product_specs": "Touring H/V/Z  Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 10",
    "ride_comfort": "Ride Comfort: 9",
    "tire_wear": "Tire Wear: 8",
    "wet_traction": "Wet Traction: 10",
    "noise_level": "Noise Level: 8"
  },
  {
    "product_id": 111,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/PotenzaRE71RS.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Bridgestone_logo.png",
    "product_name": "Bridgestone Potenza RE71RS",
    "average_rating": "",
    "review_count": "",
    "product_specs": "Ultra High Performance Summer Tires",
    "stability": "",
    "traction": "",
    "dry_traction": "",
    "ride_comfort": "",
    "tire_wear": "",
    "wet_traction": "",
    "noise_level": ""
  },
  {
    "product_id": 112,
    "product_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/full-60/h175/FirehawkASV2.png",
    "brand_img": "https://assets.firestonecompleteautocare.com/content/dam/bsro-sites/global/images/tires/brands/Firestone_logo.png",
    "product_name": "Firestone Firehawk AS V2",
    "average_rating": "4.8",
    "review_count": "(13)",
    "product_specs": "Ultra High Performance All Season Tires",
    "stability": "Stability: 0",
    "traction": "Traction: 8",
    "dry_traction": "Dry Traction: 8",
    "ride_comfort": "Ride Comfort: 8",
    "tire_wear": "Tire Wear: 10",
    "wet_traction": "Wet Traction: 8",
    "noise_level": "Noise Level: 8"
  }
]

module.exports = productData;